# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Yuanhan(William) Li
email: williamlyh@berkeley.edu
description: >- # this means to ignore newlines until "baseurl:"
  Hi! 
  I am Yuanhan Li, a senior undergraduate studying computer science at UC Berkeley.
  Welcome to my website and learn more about my research in computer architecture and other projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://william-lyh.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:  william-lyh

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide

author:
  name     : "Yuanhan Li"
  avatar   : "/assets/images/william-lyh_photo.jpg"
  bio      : "University of California, Berkeley"
  location : "Berkeley, CA"
  links:
    - label: "Email"
      icon: "far fa-fw fa-envelope"
      url: "mailto:williamlyh@berkeley.edu"
    - label: "CV"
      icon: "far fa-fw fa-file-pdf"
      url: "/assets/files/CV_YuanhanLi.pdf"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/william-lyh/"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/williamlyh/"

footer:
  links:
    - label: "Email"
      icon: "far fa-fw fa-envelope"
      url: "mailto:williamlyh@berkeley.edu"
    - label: "CV"
      icon: "far fa-fw fa-file-pdf"
      url: "/assets/files/CV_YuanhanLi.pdf"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/william-lyh/"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/williamlyh/"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
